# Generated by rust2rpm
%bcond_without check

%global crate gcsf

Name:           rust-%{crate}
Version:        0.1.25
Release:        3%{?dist}
Summary:        Filesystem based on Google Drive

License:        MIT
URL:            https://crates.io/crates/gcsf
Source:         %{crates_source}
# Initial patched metadata
# * Exclude CI files, https://github.com/harababurel/gcsf/pull/59
Patch0:         gcsf-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(chrono/default) >= 0.4.6 with crate(chrono/default) < 0.5.0)
BuildRequires:  (crate(clap/default) >= 2.32.0 with crate(clap/default) < 3.0.0)
BuildRequires:  (crate(clap/yaml) >= 2.32.0 with crate(clap/yaml) < 3.0.0)
BuildRequires:  (crate(config/default) >= 0.9.2 with crate(config/default) < 0.10.0)
BuildRequires:  (crate(ctrlc/default) >= 3.1.1 with crate(ctrlc/default) < 4.0.0)
BuildRequires:  (crate(failure/default) >= 0.1.5 with crate(failure/default) < 0.2.0)
BuildRequires:  (crate(fuse/default) >= 0.3.1 with crate(fuse/default) < 0.4.0)
BuildRequires:  (crate(google-drive3-fork/default) >= 1.0.10 with crate(google-drive3-fork/default) < 2.0.0)
BuildRequires:  (crate(hyper-native-tls/default) >= 0.3.0 with crate(hyper-native-tls/default) < 0.4.0)
BuildRequires:  (crate(hyper/default) >= 0.10.0 with crate(hyper/default) < 0.11.0)
BuildRequires:  (crate(id_tree/default) >= 1.3.0 with crate(id_tree/default) < 2.0.0)
BuildRequires:  (crate(itertools/default) >= 0.8.0 with crate(itertools/default) < 0.9.0)
BuildRequires:  (crate(lazy_static/default) >= 1.2.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(libc/default) >= 0.2.48 with crate(libc/default) < 0.3.0)
BuildRequires:  (crate(log/default) >= 0.4.6 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(lru_time_cache/default) >= 0.8.1 with crate(lru_time_cache/default) < 0.9.0)
BuildRequires:  (crate(maplit/default) >= 1.0.1 with crate(maplit/default) < 2.0.0)
BuildRequires:  (crate(mime-sniffer/default) >= 0.1.2 with crate(mime-sniffer/default) < 0.2.0)
BuildRequires:  (crate(pretty_env_logger/default) >= 0.3.0 with crate(pretty_env_logger/default) < 0.4.0)
BuildRequires:  (crate(rand/default) >= 0.6.5 with crate(rand/default) < 0.7.0)
BuildRequires:  (crate(serde/default) >= 1.0.86 with crate(serde/default) < 2.0.0)
BuildRequires:  (crate(serde_derive/default) >= 1.0.86 with crate(serde_derive/default) < 2.0.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.38 with crate(serde_json/default) < 2.0.0)
BuildRequires:  (crate(time/default) >= 0.1.42 with crate(time/default) < 0.2.0)
BuildRequires:  (crate(xdg/default) >= 2.2.0 with crate(xdg/default) < 3.0.0)
BuildRequires:  (crate(yup-oauth2/default) >= 1.0.9 with crate(yup-oauth2/default) < 2.0.0)

%global _description \
Filesystem based on Google Drive.

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate}
%{summary}.

%files       -n %{crate}
%license LICENSE
%doc README.md sample_config.toml gcsf.service
%{_bindir}/gcsf

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.25-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.25-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Feb 21 2019 Josh Stone <jistone@redhat.com> - 0.1.25-1
- Update to 0.1.25

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.24-1
- Update to 0.1.24

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.18-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Nov 27 2018 Josh Stone <jistone@redhat.com> - 0.1.18-2
- Adapt to new packaging

* Thu Oct 11 2018 Josh Stone <jistone@redhat.com> - 0.1.18-1
- Update to 0.1.18

* Sat Aug 04 2018 Josh Stone <jistone@redhat.com> - 0.1.17-1
- Update to 0.1.17

* Tue Jul 31 2018 Florian Weimer <fweimer@redhat.com> - 0.1.16-2
- Rebuild with fixed binutils

* Sat Jul 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.16-1
- Update to 0.1.16

* Thu Jul 26 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.15-1
- Initial package
